// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vwriKngs13V6h-sErq-zWzTrXaVfB6E',
    appId: '1:39706353135:web:d5e0b3c3d9ff40183faa1a',
    messagingSenderId: '39706353135',
    projectId: 'grapemaster-cf8ce',
    authDomain: 'grapemaster-cf8ce.firebaseapp.com',
    storageBucket: 'grapemaster-cf8ce.firebasestorage.app',
    measurementId: 'G-133QH4HZK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHTgczdLT_j4Ts7GLX8HHo9cXMm4W77M',
    appId: '1:39706353135:android:e30e6f5e5e43ed023faa1a',
    messagingSenderId: '39706353135',
    projectId: 'grapemaster-cf8ce',
    storageBucket: 'grapemaster-cf8ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFzqcz0bcyHVCCO09PT580dX4aUOnLl4',
    appId: '1:39706353135:ios:46597e0bce3fa5fe3faa1a',
    messagingSenderId: '39706353135',
    projectId: 'grapemaster-cf8ce',
    storageBucket: 'grapemaster-cf8ce.firebasestorage.app',
    iosBundleId: 'com.example.grapemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdFzqcz0bcyHVCCO09PT580dX4aUOnLl4',
    appId: '1:39706353135:ios:46597e0bce3fa5fe3faa1a',
    messagingSenderId: '39706353135',
    projectId: 'grapemaster-cf8ce',
    storageBucket: 'grapemaster-cf8ce.firebasestorage.app',
    iosBundleId: 'com.example.grapemaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1vwriKngs13V6h-sErq-zWzTrXaVfB6E',
    appId: '1:39706353135:web:fa27c49a909f99cc3faa1a',
    messagingSenderId: '39706353135',
    projectId: 'grapemaster-cf8ce',
    authDomain: 'grapemaster-cf8ce.firebaseapp.com',
    storageBucket: 'grapemaster-cf8ce.firebasestorage.app',
    measurementId: 'G-8VYKTRV5D3',
  );
}
